### PR TITLE
Make sure storytel works! and fixed typos

### PR DESCRIPTION
**Pull request by karesel**
Had to make sure some responses were jsonified and fixed some keys and typos. Should be good to go now

### CODE REVIEW

**Comment by karesel** [comment]
Honesetly not sure if I can be much help since I just hacked and poked at the code you had lol

**Comment by masteoo** [comment]
@karesel hello, sorry, do you have chapter marks in Storytel downloaded mp3 file? I play it with Vlc but no chapter marks

**Comment by karesel** [comment]
I don't remember seeing any chapter marks while playing with mpv sorry :/

**Comment by jo1gi** [comment]
@masteoo Do you use `--combine`? Don't think it will add chapter marks if you don't.

**Comment by masteoo** [comment]
@karesel ok thanks..
@jo1gi hello, thanks I will try, I did't know I have to use _--combine_ because the final mp3 files are only one file and during the execution of the script I read 
'..saving chapter
saving cover...'
so I thought metadata were all saved in the final mp3 (example attached renamed .zip)
[Sherlock Holmes e un caso d'identità (1).zip](https://github.com/jo1gi/audiobook-dl/files/13306920/Sherlock.Holmes.e.un.caso.d.identita.1.zip)

**Comment by jo1gi** [comment]
You don't have to, if it is a single file. My mistake.

**Comment by masteoo** [comment]
> @masteoo You don't have to, if it is a single file. My mistake.

Ok thanks, if you have a Storytel account you can see by yourself (in Storytel app audiobooks have chapters)

**Comment by masteoo** [comment]
@jo1gi do u think I have to open an issue? Thanks

**Comment by jo1gi** [comment]
You don't have to, but it would be nice. It just makes it easier to track problems.

**Comment by jo1gi** [comment]
You don't have to, but it would be nice. It just makes it easier to track problems.

**Pull request merged**
